on:
 push:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--ignore E501,E704'
